### ISSUE TITLE
Missed Message ssl_closed

### ISSUE THREAD

**Issue by isaacsanders** [elixir-ecto/postgrex#482] opened 2019-10-15 20:27 UTC
I get this message

```
Postgrex.Protocol (#PID<0.488.0>) missed message: {:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.2195>, :tls_connection, :undefined}, [#PID<0.526.0>, #PID<0.520.0>]}}
```

When using the configuration like the following: 

```
config :my_app, MyApp.Repo,
  parameters: [
    application_name: "my_app"
  ]
```

But not when I use the `after_connect` to set the `application_name`.

**Comment by isaacsanders** [comment] 2019-10-15 20:40
This may be due to using pgPool II

**Comment by josevalim** [comment] 2019-10-15 20:58
Do you get the message every time? Can you still run queries after you get the error above?

It may be pgPool is not enjoying those parameters being set at connection time, and it requires them to be set after the connection is established.

Can you please provide precise steps to reproduce the error? Thanks.

**Comment by isaacsanders** [comment] 2019-10-15 21:12
The application fails to start.

**Comment by josevalim** [comment] 2019-10-15 21:13
So I would say this is behaving correctly. pgpool is closing the connections, it is most likely not telling us why, so we are logging the socket was closed. What would you expect instead?

**Comment by isaacsanders** [comment] 2019-10-15 21:14
When we circumvent and connect to the database underlying the pool, the message isn't presented.

**Comment by josevalim** [comment] 2019-10-15 21:17
@isaacsanders and does the app boot in such cases?

**Comment by isaacsanders** [comment] 2019-10-15 21:27
With pgpool, the app never starts.
On the bare server, the app starts.

**Comment by isaacsanders** [comment] 2019-10-15 21:27
pgpool version 3.7.5

**Comment by josevalim** [comment] 2019-10-15 21:41
Right, that's my point. pgpool is the one closing the connection. There is no much we can do when the pool decides to close the connection abruptly. If it works with pg but not with pgpool, it is a reasonable assumption that pgpool is at fault, since pg is meant to be the standard. Do you see anything in pgpool logs that may indicate it is a bug on our end? tks.

**Comment by josevalim** [comment] 2019-10-16 06:56
Closing per the above. If you have more evidence, such as error logs, that the issue is on our end and a way for us to reproduce the error, we will gladly reopen. Thanks!

**Closed by josevalim** 2019-10-16 06:56 UTC

**Comment by isaacsanders** [comment] 2019-10-16 13:43
It is probably just on the pgpool side
