### ISSUE TITLE
Error Postgrex.DefaultTypes timestamp with  Postgres Wire Protocol v3 compatible db :  CrateDB

### ISSUE THREAD

**Issue by cocoaway** [elixir-ecto/postgrex#642] opened 2023-02-02 17:25 UTC
### Elixir version

1.14.0

### Database and Version

Postgres Wire Protocol v3 CrateDB v5.1

### Postgrex Version

0.16.5

### Current behavior

When a query requests for a timestamp this error is raised :

`
{:error,
 %Postgrex.QueryError{
   message: "type 'timestamp without time zone' can not be handled by the types module Postgrex.DefaultTypes"
 }}
`

or, depending of the timestamp type in the table,

`type 'timestamptz' can not be handled by the types module Postgrex.DefaultTypes`

the query is 
`
SELECT * FROM doc.mytable 
`

Table contains timestamp field.

Other queries that don't return timestamps run fine with Postgrex.

CrateDB has no issues when the same query is made  with Beekeeper Studio, DBeaver, Python Alchemy.

The timestamp type is 'timestamp with time zone'  or 'timestamp without time zone'.

 

### Expected behavior

Returning records that contain timestamps.

**Comment by josevalim** [comment] 2023-02-02 17:46
Can you run this query on `Cratedb`?

    SELECT typname, typsend FROM pg_type;

In Postgres, it returns:

```
demo_dev=# SELECT typname, typsend FROM pg_type;
                typname                 |            typsend
----------------------------------------+--------------------------------
 date                                   | date_send
 time                                   | time_send
 timestamp                              | timestamp_send
 timestamptz                            | timestamptz_send
 interval                               | interval_send
 timetz                                 | timetz_send
```

Note that it returns `timestamp` and `timestamptz`. In other words, while the type is named `timestamp without time zone` in the SQL queries, _internally_ there is no such type. The internal types must be named `timestamp` and `timestamptz`.

So if the results for CrateDB do not match, then that's a bug in the implementation of the Postgres Wire Protocol.

**Comment by cocoaway** [comment] 2023-02-02 18:40
Here is the query result.
Thx.

<img width="475" alt="Screenshot 2023-02-02 alle 19 32 04" src="https://user-images.githubusercontent.com/5250613/216419334-03fdd032-5b10-43ae-9ee7-8e00be604799.png">

**Comment by greg-rychlewski** [comment] 2023-02-02 18:49
The other drivers are probably using the text protocol. `typsend` is the function used to convert the data to the binary format. It's not possible for a function to be named with space like `timestamp without time zonesend`.

**Comment by cocoaway** [comment] 2023-02-02 18:56
Thanks for now, I'll check with Crate guys about this issue.

**Comment by greg-rychlewski** [comment] 2023-02-04 01:29
Thanks for the update. Since it seems like the issue is with CrateDB I'll close this issue but feel free to reach out in case there's anything else we can do.

**Closed by greg-rychlewski** 2023-02-04 01:29 UTC
Labels: Kind:Bug

**Comment by mfussenegger** [comment] 2023-02-06 07:44
Out of curiosity: Why does postgrex depend on the type name and typsend information?

Other clients we've tested work fine with binary serialization as they only depend on the `oid` of the type.

**Comment by greg-rychlewski** [comment] 2023-02-06 08:27
Since Postgrex also uses the binary protocol for user defined types I don't think OIDs are the same across all machines.

**Comment by ericmj** [comment] 2023-02-06 12:37
Also, many types share data format and encoding which means we can handle them all by just matching the function name.
