### ISSUE TITLE
Not enough context in error to diagnose

### ISSUE THREAD

**Issue by nathanl** [elixir-ecto/postgrex#401] opened 2018-09-06 20:58 UTC
I just ran into an edge case where the error message I got from `Postgrex` was not helpful. This may not be worth solving, and it may not be the right place to post this, so feel free to dismiss this.

We have a view that contains a subset of another table. Something like:

```elixir
    CREATE VIEW current_games AS
      SELECT * FROM games
      WHERE started_at is not null and ended_at is null;
```

That view is treated as a relation and "hydrated" using the same schema as the underlying table:

```elixir
    has_one(
      :current_game,
      {"current_games", Game}
    )
```

We had a migration that added a new column "legacy_id" to `games` (and to several other tables). We started getting errors like:

```elixir
    ** (Postgrex.Error) ERROR 42703 (undefined_column): column i0.legacy_id does not exist
        (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
        (ecto) lib/ecto/repo/queryable.ex:133: Ecto.Repo.Queryable.execute/5
        (ecto) lib/ecto/repo/queryable.ex:37: Ecto.Repo.Queryable.all/4
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
        (elixir) lib/enum.ex:1314: Enum."-map/2-lists^map/1-0-"/2
```

The issue turned out to be that the view had baked in the exact list of columns from the `SELECT *`, and thus did not have the new column from its underlying table. So when we tried to `Repo.preload` the view-based association, it caused the error above, as it couldn't query the view for all the columns the schema defined.

I don't know whether anything can or should be improved here, but this was frustrating to debug because the stack trace didn't tell me anything helpful. It didn't point to any code in the project, and `column i0.legacy_id`, being an alias, didn't tell me which table was the problem.

Would it be possible to surface the non-aliased table name in cases like this? Or is there a way to get a stack trace that points back to the `Repo.preload`?

Like I said, feel free to close this if it's too weird to care about.

**Comment by fishcakez** [comment] 2018-09-12 14:47
Do we get any more information with Ecto `788847c` and its deps?

**Comment by josevalim** [comment] 2018-09-19 08:54
@fishcakez I don't think a more recent Ecto would help because Postgres is not sending the information @nathanl wants in the first place. @nathanl, I will go ahead and close this issue then as there isn't much we can do. You may want to report this upstream to Postgres itself, especially if you can reproduce it in psql.

**Closed by josevalim** 2018-09-19 08:54 UTC

**Comment by fishcakez** [comment] 2018-09-19 13:35
@josevalim @nathanl that commit of Ecto has a version of postgrex with improved error messages. I think @nathanl triggered those changes last time too. I dont think we can get more info that in that change.
