### ISSUE TITLE
Add Static Type Mapping Configurations

### ISSUE THREAD

**Issue by Linicks** [elixir-ecto/postgrex#213] opened 2016-07-06 19:08 UTC
All,
  In a recent attempt to use Postgrex with CockroachDB's Postgresql interface, I ran into issues leading to the following conversations on Google groups:

[Elixir-Talk]
- https://groups.google.com/forum/#!topic/elixir-lang-talk/5GjZryBTusI

[CockroachDB]
- https://groups.google.com/forum/#!topic/cockroach-db/WVm4P8PX1cM

The summary of these conversations is that Postgrex currently relies on facilities that are specific to Posgtresql like arrays and pg_type.  These features allow Postgrex to create a dynamic mapping of database types to Elixir types.  Unfortunately, CockroachDB doesn't currently implement array, and pg_type, but does provide a static type map here:(https://github.com/cockroachdb/cockroach/blob/master/sql/pgwire/types.go#L362).  To accommodate these types of use cases, without creating a new version of Postgrex just for CockroachDB, and possibly other databases that implement the Postgresql protocol, José Valim suggested the following possible solution:

"Maybe we can allow a types configuration that you would set in the format that Postgrex expects and, when this configuration is available, Postgrex would no longer perform the query."

Thanks!
--Nick Pavlica

**Comment by fishcakez** [comment] 2016-07-09 00:04
Currently we have an undocumented option `types: boolean` for internal use. I guess we could change this to `types: :query | [%Postgrex.TypeInfo{}]` and jump straight to `Postgrex.Types.associate_extensions_with_types` when bootstrapping with a list of types.

It would be interesting if this change would also allow support for redshift - no idea tbh - as it would be simple change. I would be concerned about making more changes than that to support other databases if none of the maintainers are using them.

Please feel free to try this change @Linicks but no promises on merging it.

**Comment by talentdeficit** [comment] 2016-07-09 04:07
allowing static type mappings would allow redshift support also, as it's currently blocked on a similar issue

**Comment by josevalim** [comment] 2016-07-09 06:53
Maybe we could include some tests to guarantee it at least bootstrap on
those other DBs and add them to Travis?

On Saturday, July 9, 2016, alisdair sullivan <notifications@github.com>
wrote:

> allowing static type mappings would allow redshift support also, as it's
> currently blocked on a similar issue
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/elixir-ecto/postgrex/issues/213#issuecomment-231513718>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAAlbs9l7bFAHIIQRVP7EyqVFxJ3gtk3ks5qTx57gaJpZM4JGZ0U>
> .
>


-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Comment by talentdeficit** [comment] 2016-07-09 16:11
the static type table required by cockroachdb:
```csv
16,bool,boolsend,boolrecv,boolout,boolin,0,0,{}
17,bytea,byteasend,bytearecv,byteaout,byteain,0,0,{}
20,int8,int8send,int8recv,int8out,int8in,0,0,{}
21,int2,int2send,int2recv,int2out,int2in,0,0,{}
23,int4,int4send,int4recv,int4out,int4in,0,0,{}
25,text,textsend,textrecv,textout,textin,0,0,{}
700,float4,float4send,float4recv,float4out,float4in,0,0,{}
701,float8,float8send,float8recv,float8out,float8in,0,0,{}
1043,varchar,varcharsend,varcharrecv,varcharout,varcharin,0,0,{}
1082,date,date_send,date_recv,date_out,date_in,0,0,{}
1114,timestamp,timestamp_send,timestamp_recv,timestamp_out,timestamp_in,0,0,{}
1184,timestamptz,timestamptz_send,timestamptz_recv,timestamptz_out,timestamptz_in,0,0,{}
1186,interval,interval_send,interval_recv,interval_out,interval_in,0,0,{}
1700,numeric,numeric_send,numeric_recv,numeric_out,numeric_in,0,0,{}
```

the static table required by redshift:
```csv
16,bool,boolsend,boolrecv,boolout,boolin,0,0,{}
18,char,charsend,charrecv,charout,charin,0,0,{}
20,int8,int8send,int8recv,int8out,int8in,0,0,{}
21,int2,int2send,int2recv,int2out,int2in,0,0,{}
23,int4,int4send,int4recv,int4out,int4in,0,0,{}
25,text,textsend,textrecv,textout,textin,0,0,{}
700,float4,float4send,float4recv,float4out,float4in,0,0,{}
701,float8,float8send,float8recv,float8out,float8in,0,0,{}
1042,bpchar,bpcharsend,bpcharrecv,bpcharout,bpcharin,0,0,{}
1043,varchar,varcharsend,varcharrecv,varcharout,varcharin,0,0,{}
1082,date,date_send,date_recv,date_out,date_in,0,0,{}
1114,timestamp,timestamp_send,timestamp_recv,timestamp_out,timestamp_in,0,0,{}
1700,numeric,numeric_send,numeric_recv,numeric_out,numeric_in,0,0,{}
```

**Comment by fishcakez** [comment] 2016-07-09 16:16
This is great @talentdeficit. Is it possible for us to automatically detect the backend before we send the bootstrap query?

**Comment by talentdeficit** [comment] 2016-07-09 16:31
output of `SELECT version()` on postgres 9.4.5:
```
                                                    version                                                    
---------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.5 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit
```

output of `SELECT version()` on redshift:
```
                                                         version                                                          
--------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.1069
```

output of `SELECT version()` on cockroachdb latest beta
```
+------------------------------------------------------------------------------+
|                                  version()                                   |
+------------------------------------------------------------------------------+
| CockroachDB beta-20160629 (darwin amd64, built 2016/06/29 19:36:14, go1.6.2) |
+------------------------------------------------------------------------------+
```

**Comment by talentdeficit** [comment] 2016-07-09 16:32
postgres exposes both numeric and easier to parse version identifiers to via `SHOW server_version` and `SHOW server_version_num` but cockroachdb doesn't support `SHOW` and redshift doesn't allow sufficient permissions to use `SHOW`

**Comment by fishcakez** [comment] 2016-07-09 16:40
@talentdeficit do we get parameters from the database after auth that we can use? For example we get the version from postgres. See `Postgrex.parameters/1`.

**Comment by talentdeficit** [comment] 2016-07-09 16:58
with the modification in #215 i get the following with redshift:
```elixir
iex(2)> Postgrex.parameters(pid)
%{"TimeZone" => "UTC", "client_encoding" => "UNICODE",
  "datestyle" => "ISO, MDY", "gconf_case_sensitive" => "on",
  "integer_datetimes" => "on", "is_superuser" => "on",
  "max_numeric_precision" => "38", "max_varchar_size" => "65535",
  "padb_revision" => "865e23b4a3", "padb_version" => "",
  "server_encoding" => "UNICODE", "server_version" => "8.0.2",
  "session_authorization" => "olap", "timezone_abbreviations" => "Default"}
```

i think but am not convinced that cockroachdb returns:
```elixir
%{"DateStyle" => "ISO", "client_encoding" => "UTF8",
  "server_version" => "9.5.0"}
```

**Comment by Linicks** [comment] 2016-07-13 22:28
All,
  With #215 it looks like you can connect to both Redshift, and CockroachDB.  I'm curious if there are any major roadblocks keeping this issue from moving this forward?

Thanks!
--Nick

**Comment by talentdeficit** [comment] 2016-07-13 22:40
#215 helps with redshift but not cockroachdb. cockroachdb will need the static table

**Comment by Linicks** [comment] 2016-07-13 23:13
I wounder if it makes sense to have a "database profile(s)" for various flavors of Postgresql related databases.  By default it would load the stock Postgresql profile that would contain the type acquisition query, etc.  Then for other Databases like Redshift, CockroachDB, and others, a profile configuration could be set to a profile that contains any necessary queries, type maps, tests, etc. to get them working.   Just a thought..

-- Nick

**Comment by talentdeficit** [comment] 2016-07-14 04:15
note: i'm not a postgrex maintainer so i can't actually help you get any of this merged, but here's what i think:

part of the problem is that postgrex takes advantage of postgres features that aren't strictly related to the protocol like anonymous portals for prepared queries. redshift in particular lacks support for most of them and i doubt cockroachdb supports them either, although i haven't run the test suite against it yet

overriding the type server bootstrap is pretty straight forward but that leaves feature compatibility an open question. probably the best way to move things forward is to try and run the existing test suite against cockroachdb using [this](https://github.com/talentdeficit/postgrex/tree/cockroachdb) branch that uses a static table query to bootstrap the types cockroachdb supports and come up with a list of features that need to be disabled when using cockroachdb

the other problem that needs a solution is detecting when connecting to a cockroachdb. currently as seen above it reports itself as postgres 9.5.0

**Comment by tlvenn** [comment] 2016-07-20 14:58
>the other problem that needs a solution is detecting when connecting to a cockroachdb. currently as seen above it reports itself as postgres 9.5.0

But if a flavor (db profile as named by @Linicks ) can be added to the config, why would postgrex try to detect the flavor itself ?

**Comment by ericmj** [comment] 2016-07-20 16:55
> Then for other Databases like Redshift, CockroachDB, and others, a profile configuration could be set to a profile that contains any necessary queries, type maps, tests, etc. to get them working. Just a thought..

This sounds like a pain to test and maintain. This would have to be some kind of adapter functionality where the different profiles are maintained in separate libraries.

**Comment by tlvenn** [comment] 2016-07-21 00:55
Ya totally agree @ericmj , postgrex should provide a pluggable way for this and the matching postgresql adaptor and that's it. Then the community can develop test and maintain other adaptors.

**Comment by tlvenn** [comment] 2016-07-29 15:05
If there is a reached consensus that an adaptor is the right way to approach this, how should we move forward @ericmj ? CockroachDB is a pretty exciting new DB and it would be pretty awesome to add Elixir to their growing list of supported languages.

**Comment by fishcakez** [comment] 2016-07-29 17:38
I am closing this because it is too much of a burden to support either.

redshift can't be tested on CI so it is difficult to maintain support.

cockroachdb is not compatible enough with postgreSQL, at least:
* Ignores closing prepared query protocol packets
* Savepoints aren't supported and when followed by a sync message only returns an error message and not the expected ready message
* Sends errors messages with code `internal_error` when postgreSQL would return a more specific error code

Once/if those three issues are resolved we might be able to revisit this.

**Closed by fishcakez** 2016-07-29 17:38 UTC

**Comment by tlvenn** [comment] 2016-07-30 06:59
Hi @fishcakez, could you elaborate a little bit on why the savepoint feature is important for the driver to work properly ? In which context are savepoints used without the command being sent by the client explicitly ? Thanks.

**Comment by fishcakez** [comment] 2016-07-30 10:08
@tlvenn its wasn't that we need the savepoints themselves, it was rather that after the error we had problems with the protocol. I will check that the problem is not on postgrex's end.

**Comment by fishcakez** [comment] 2016-07-30 10:25
@tlvenn AH okay we can ignore the savepoint one as this is a protocol bug in postgrex.

**Comment by fishcakez** [comment] 2016-07-30 12:14
@tlvenn there is also an issue with `numeric`. An extra 2 bytes are appended to numeric values in row data messages.

**Comment by tlvenn** [comment] 2016-07-30 15:13
Thanks for the clarification on savepoint and raising the issue around the handling of numeric @fishcakez.
