### ISSUE TITLE
Postgrex.Notifications does not receive notifications with local Postgres from other processes

### ISSUE THREAD

**Issue by JonRowe** [elixir-ecto/postgrex#427] opened 2018-11-12 13:35 UTC
When using my local Postgres server for development, (OS X, home brew installed 10.5), Postgrex will not receive notifications issued from outside the process. I'm testing this by issuing notifications as `NOTIFY channel, 'payload';` and by the use of a trigger. This works across process in the command line (`psql` to `psql`) but the listener will not register it. Similarly I can trigger notifications inside the app by causing the trigger to be fired (so the setup works, its just something funny is going on).

Am I doing something wrong? I don't want to keep following this path if I can't receive notifications from outside my process, my use case is I have some lambdas that will be firing these triggers, and I'm using the notify to tell down stream subscribers of this data.

This is my listener code:

```
defmodule Listener do
  use GenServer

  require Logger
 
  def start_link(opts) do
    GenServer.start_link(__MODULE__, opts)
  end

  def init(_opts) do
    channel = "channel"

    pg_config = Application.get_env(:name, Repo)
    {:ok, pid} = Postgrex.Notifications.start_link(pg_config)
    {:ok, ref} = Postgrex.Notifications.listen(pid, channel)
    {:ok, %{pid: pid, channel: channel, ref: ref}}
  end

  def handle_info({:notification, pid, ref, channel, message}, %{channel: channel, pid: pid, ref: ref} = state) do
    Logger.debug "Notification received, #{channel}, #{message}"
    {:noreply, state}
  end

  def handle_info(something, state) do
    Logger.error "Unexpected message: #{something}"
    {:noreply, state}
  end
end
```

**Comment by josevalim** [comment] 2018-11-12 15:32
Hi @JonRowe! Can you please provide a sample setup that reproduces this issue? Maybe a small repo with a shell script or similar we can run. Thank you!

**Comment by JonRowe** [comment] 2018-11-12 16:11
@josevalim I certainly can, https://github.com/JonRowe/postgres-notification-issue, see read me for instructions.

**Comment by happysalada** [comment] 2018-11-20 00:12
great that you have had this issue (not great that you've had it, but now I feel less crazy). I have had this issue on production for a while now. However in my development environment it always worked. I put my code there
https://elixirforum.com/t/postgrex-notifications-sometimes-doesnt-receive-notifications-on-production/17937
(it's essentially the same as yours)

**Comment by JonRowe** [comment] 2018-11-20 10:14
I wonder if its a file system case sensitivity issue? I'm on OS X and thus on the default case insensitive filesystem. What are you dev/prod file systems like/

**Comment by happysalada** [comment] 2018-11-20 11:11
The weird thing for me, is that on production I have seen it work sometimes, and sometimes just not. 
When it doesn't work, I've tried inspecting the process, and everything runs just fine.

The names of the channel I'm listening to are 'insert, update, delete' all small case all in one word.
I build my production image with alpine elixir and deploy it on an alpine image. On dev I have OS X.
I couldn't find anything on if alpine was case sensitive or not

**Comment by happysalada** [comment] 2018-11-30 01:19
One thing I observed in my logs, is that sometimes I get
```
10:14:36.051 [error] Postgrex.Protocol (#PID<0.1339.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.1494.0> exited
```
do you get something similar, in your logs somewhere?
I'm wondering, if the db connection gets closed for some reason, and the listener doesn't crash, but obviously he doesn't receive messages anymore. Just a thought.

**Comment by happysalada** [comment] 2018-11-30 08:09
Looking at the code briefly, there doesn't seem to be any option to enable it. It seems that by default it will ping every 5s right? By "make sure it's is enabled" you mean, that I haven't set idle_timeout value to something too big?

**Comment by josevalim** [comment] 2018-11-30 08:37
Yes.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by happysalada** [comment] 2018-11-30 13:56
ok it's definitely on then. On development I have seen this once. I have it on on production as well. I'll report if I see anything. It might take some time though.

**Comment by josevalim** [comment] 2019-07-16 19:29
Closing this. Please let us know if there is anything that can be done from our side. Thank you!

**Comment by JonRowe** [comment] 2019-07-17 15:19
Verified that this is still broken on `0.14.3` with Elixir 1.9, this can be replicated with my reproduction repo quite readily, it uses only postgrex and postgres. So it needs to be fixed in postgrex...

**Comment by josevalim** [comment] 2019-07-17 19:56
Somehow I missed the app, I am sorry. So I took a look into this and you are running into Postgres issues with case sensitivity: https://dev.to/lefebvre/dont-get-bit-by-postgresql-case-sensitivity--457i

In particular, if I change your bin/client to do use `NOTIFY \"channelName\", 'Oh hai!';`, then it works.

That's because when Postgrex subscribes, it also uses quotes, so it doesn't allow any downcase. I don't there is any proper outcome here besides making people aware of such gotcha in the docs.

**Comment by JonRowe** [comment] 2019-07-17 20:03
Cool, I'm happy to write something up, where would be the best place to mention this in the docs? https://hexdocs.pm/postgrex/Postgrex.Notifications.html#summary maybe?

**Comment by josevalim** [comment] 2019-07-17 20:09
@JonRowe oops, sorry, I already wrote something meanwhile! :(

**Closed** 2019-07-17 20:09 UTC
Labels: Kind:Bug

**Comment by JonRowe** [comment] 2019-07-17 20:11
No worries! Just trying to make the load easier!
