### ISSUE TITLE
bootstrap_query cost too much time

### ISSUE THREAD

**Issue by DavidAlphaFox** [elixir-ecto/postgrex#136] opened 2016-01-03 09:20 UTC
Dear author,
I use postgresx 0.10.0 with PostgreSQL 9.4.4.
I found that the bootstrap_query cost too much time, then the server side close the connection.

I saw this in postgresSQL:

LOG:  statement: SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,
           t.typelem, coalesce(r.rngsubtype, 0), ARRAY (
      SELECT a.atttypid
      FROM pg_attribute AS a
      WHERE a.attrelid = t.typrelid AND a.attnum > 0 AND NOT a.attisdropped
      ORDER BY a.attnum
    )
    FROM pg_type AS t
    LEFT JOIN pg_range AS r ON r.rngtypid = t.oid
    WHERE
      t.typname::text = ANY ((ARRAY['citext', 'hstore', 'jsonb', 'json'])::text[]) OR
      t.typsend::text = ANY ((ARRAY['array_send', 'range_send', 'record_send', 'cidsend', 'xidsend', 'regtypesend', 'regclasssend', 'regoperatorsend', 'regopersend', 'regproceduresend', 'regprocsend', 'oidsend', 'macaddr_send', 'cidr_send', 'inet_send', 'unknownsend', 'tidsend', 'enum_send', 'interval_send', 'timestamptz_send', 'timestamp_send', 'timetz_send', 'time_send', 'date_send', 'uuid_send', 'numeric_send', 'float8send', 'float4send', 'int8send', 'int4send', 'int2send', 'byteasend', 'varcharsend', 'textsend', 'bpcharsend', 'boolsend', 'void_send'])::text[]) OR
      t.typreceive::text = ANY ((ARRAY[])::text[]) OR
      t.typoutput::text = ANY ((ARRAY[])::text[]) OR
      t.typinput::text = ANY ((ARRAY[])::text[]);
LOG:  could not receive data from client: Operation timed out
LOG:  connection received: host=10.99.0.11 port=26380

I don't know why postgrex need this, and I want to know how to fix it.

**Comment by josevalim** [comment] 2016-01-03 09:34
We need the types information so we know how to decode types. I would try a couple things:

1. Does the issue happen on Postgrex 0.9.0?
2. Have you configured the timeouts in your database in any way?

**Comment by DavidAlphaFox** [comment] 2016-01-03 11:40
I did`t use Postgrex 0.9.0. And I don`t configure any timeout in my database. I found that if the network bandwidth is very low such as only 10KB/s, it will be happened. I also found that the client throw a "tcp recv timeout" exception.

**Comment by josevalim** [comment] 2016-01-03 11:51
There is a timeout value you can pass when you call `Postgrex.Connection.start_link`: https://github.com/ericmj/postgrex/blob/403c0b3b36f5defecee259247cb261e4b6817f12/lib/postgrex/protocol.ex#L23. Just increase the value, like `timeout: 30_000`.

If you are using Ecto, it can be configured by setting connect_timeout in your Repo configuration.

**Comment by DavidAlphaFox** [comment] 2016-01-03 12:09
Thanks a lot, I see that. I found it would cost nearly two minutes in my wireless network to connect to a remote PostgreSQL.But it works.

**Comment by ericmj** [comment] 2016-01-04 12:17
Unfortunately postgrex needs this information due to how it encodes and decodes postgresql types. It would be possible to use simpler encoding/decoding without needing this information but that is not a goal of this driver at the moment.

**Comment by fishcakez** [comment] 2016-01-04 13:51
If the bootstrap query is that slow other queries will be too. If they are not there is a bug with bootstrap code :(.

**Comment by ericmj** [comment] 2016-01-04 13:56
@fishcakez To be fair the bootstrap query is a pretty big unindexed query and can actually quite take some time if you have slow database with lots of types.

**Comment by fishcakez** [comment] 2016-01-04 14:33
Ah I haven't seen it take more than a second so was a bit worried.

**Comment by DavidAlphaFox** [comment] 2016-01-07 03:57
@fishcakez I don't think this is a bug. I think I should improve my network in my workplace. And I think fetch information of types to encoding/decoding is a great idea.

**Comment by armed** [comment] 2016-09-26 06:48
Sorry for asking here after issue is closed, but I need advice. What to do, if I want to connect to Postgresql database with more than 15k tables (30+ schemas with 500+ tables each). And I need pool for 5-7 connections to each shema. All pool initialization takes ages and 100% CPU load. 

Thanks.

**Comment by ericmj** [comment] 2016-09-26 07:59
Maybe we can use the `typnamespace` column on `pg_type` to query on a subset of schemas. Would that work for you @armed?

**Comment by armed** [comment] 2016-09-26 08:11
@ericmj that would be great!

**Comment by ericmj** [comment] 2016-09-26 09:27
Types are shared between connections to the same database, but I think stale ones are refreshed for every new connection, this can of course cause problems if you have 15k tables since huge queries will be made. It looks like we need to make the bootstrapping more configurable.

@fishcakez knows the code better than me so I'll leave it to him to explain how it works and why.

**Comment by fishcakez** [comment] 2016-09-26 11:12
Hi @armed.

We share type information between connections to the same database with same extension options. The first connection to connect to a backend will gain a lock and query the type tables and setup the type cache. All future connections to the same backend will do the same query except exclude all oids currently in the type cache. The query for new types was only added in 0.12 so please can you verify the postgrex entry in your mix.lock file. This issue was opened/closed prior to the new query added in 0.12.

If you can start your pools and then run this code to let us know the results:
```elixir
:sys.get_state(Postgrex.TypeServer) |> elem(0) |> Map.size()
:sys.get_state(Postgrex.TypeServer) |> elem(0) |> Map.values() |> hd() |> elem(3) |> :ets.info(:size)
```
Once you've done could you stop all the pools and immediately restart them all at once - hopefully your supervision tree allows this. Does the same problem occur?

**Comment by fishcakez** [comment] 2016-09-26 15:59
@armed could you try #241 and report back on that? If that works please ignore my previous comment.

**Comment by armed** [comment] 2016-09-27 05:40
Hey, @fishcakez. I checked #241 and it works as you said. Only first connection gathers type information. Neat!

**Comment by fishcakez** [comment] 2016-09-27 09:55
@armed so it solved your issue?

**Comment by armed** [comment] 2016-09-27 09:55
@fishcakez yes. Thanks.

**Comment by josevalim** [comment] 2016-09-27 10:56
@fishcakez :heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by safwank** [comment] 2016-11-04 01:17
Hi guys, I recently upgraded `postgrex` to 0.12.1 from 0.11.2 and started having the same problem as @armed. We have a `postgres` structure similar to @armed, albeit with hundreds of schemas and 30 or so tables per schema. 

When the app boostraps it just smashed our production `postgres`. During off peak it normally gets around 40% utilization, but with 0.12.1 it went all the way up to 100%. This doesn't happen in our staging environment which obviously gets much lower utilization. After some digging we narrowed the problem down to the above query.

It's weird because the release was supposed to fix the problem, but in my case it was the other way around. What am I missing?

**Comment by fishcakez** [comment] 2016-11-04 01:31
@safwank, the issue @armed had was (re?)introduced in 0.12.0 and we believed fixed in 0.12.1. Please can you verify you are on 0.12.1 and we will reopen this issue.

**Comment by safwank** [comment] 2016-11-04 21:37
@fishcakez Yup, we WERE on 0.12.1 but reverted to 0.11.2 after the botched production deployment.

**Comment by fishcakez** [comment] 2016-11-04 23:24
We should only run a single one of those queries at a time, it might be hard to reproduce.

**Comment by fishcakez** [comment] 2016-11-09 12:49
@safwank could you post the configuration of postgrex? Are you using `DBConnection.Poolboy` and `:pool_overflow`, or `:poolboy` and `:max_overflow` by any chance?

**Comment by safwank** [comment] 2016-11-10 00:37
@fishcakez I'm using `postgrex` via `ecto`. Here's the `Repo` config:

**Comment by fishcakez** [comment] 2016-11-10 00:57
Thanks @safwank, so standard callback. Do you get any log messages when things are going bad? I will look at this tomorrow because Ecto 2.1requires at least 0.12.

**Comment by safwank** [comment] 2016-11-10 03:15
```

**Comment by safwank** [comment] 2016-11-10 03:24
Here's a snippet of the error log:

```
[error] Postgrex.Protocol (#PID<0.1628.0>) failed to connect: ** (DBConnection.ConnectionError) tcp send: closed
 [error] Postgrex.Protocol (#PID<0.1644.0>) failed to connect: ** (DBConnection.ConnectionError) tcp recv: closed
** (EXIT) time out
(elixir) lib/gen_server.ex:604: GenServer.call/3
(postgrex) lib/postgrex/protocol.ex:486: Postgrex.Protocol.bootstrap/3
(postgrex) lib/postgrex/protocol.ex:353: Postgrex.Protocol.handshake/2
(db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
(connection) lib/connection.ex:741: Connection.connect/3
(stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
00:47:46.762 [error] GenServer #PID<0.1631.0> terminating
(stdlib) gen_server.erl:681: :gen_server.handle_msg/5
(stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
=CRASH REPORT==== 3-Nov-2016::00:47:46 ===
crasher:
initial call: Elixir.DBConnection.Connection:init/1
pid: <0.1631.0>
registered_name: []
exception exit: {timeout,
{'Elixir.GenServer',call,
['Elixir.Postgrex.TypeServer',
{fetch,
{"postgres.myapp.io",5432,<<"myapp">>,copy,
[{'Elixir.Ecto.Adapters.Postgres.DateTime',
[]},
{'Elixir.Postgrex.Extensions.JSON',
[{library,'Elixir.Poison'}]}]}},
60000]}}
in function gen_server:terminate/7 (gen_server.erl, line 814)
ancestors: [<0.1627.0>,'Elixir.MyApp.Repo.Pool','Elixir.MyApp.Repo',
'Elixir.MyApp.Supervisor',<0.1623.0>]
messages: []
links: [<0.1626.0>,<0.1627.0>,<0.1584.0>,#Port<0.4625>]
dictionary: []
trap_exit: false
status: running
heap_size: 1598
stack_size: 27
reductions: 3794
neighbours:
=SUPERVISOR REPORT==== 3-Nov-2016::00:47:46 ===
Supervisor: {<0.1627.0>,poolboy_sup}
** (stop) exited in: GenServer.call(Postgrex.TypeServer, {:fetch, {'postgres.myapp.io', 5432, "myapp", :copy, [{Ecto.Adapters.Postgres.DateTime, []}, {Postgrex.Extensions.JSON, [library: Poison]}]}}, 60000)
```

**Comment by fishcakez** [comment] 2016-11-10 18:13
The top lines
```
[error] Postgrex.Protocol (#PID<0.1628.0>) failed to connect: ** (DBConnection.ConnectionError) tcp send: closed
[error] Postgrex.Protocol (#PID<0.1644.0>) failed to connect: ** (DBConnection.ConnectionError) tcp recv: closed
```
These are likely because the handshake + bootstrap took longer than `:timeout`. We don't log here that we are closing the socket on timeout. We should definitely do that.

The next bit seems to be missing the first lines, but it would be something about exiting in the call `GenServer.call.(Postgrex.TypeServer, ... 60_000)`:
```
** (EXIT) time out
(elixir) lib/gen_server.ex:604: GenServer.call/3
(postgrex) lib/postgrex/protocol.ex:486: Postgrex.Protocol.bootstrap/3
(postgrex) lib/postgrex/protocol.ex:353: Postgrex.Protocol.handshake/2
(db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
(connection) lib/connection.ex:741: Connection.connect/3
(stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
00:47:46.762 [error] GenServer #PID<0.1631.0> terminating
(stdlib) gen_server.erl:681: :gen_server.handle_msg/5
(stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
```
This means a connection waited 60 seconds for a lock to bootstrap or for another process to bootstrap but it did not get gain the lock and another process didn't successfully bootstrapped in that time. The rest of the log is other logs generated on the same crash.

This is both good and bad news I think. Its good because it means the lock is working. Its bad because it means processes timeout before they bootstrap and we never bootstrap but constantly retry.

The next bootstrap does not wait for the postgres backend receiving the bootstrap query to be shutdown, so there could be some overlap. This means we always have 1 or 2 bootstrap queries running. It might be possible to resolve this by upping the timeout on the connection processes. I would recommend passing it to Repo.start_link options, rather than in configuration because the configuration will also change the transaction timeout. We should add a `handshake_timeout` as well as the log message so we can differentiate that configuration. I am unsure how we can safely test this solution without a script that can reproduce the issue.

**Comment by safwank** [comment] 2016-11-14 00:30
@fishcakez I just made a second attempt at deploying to production with v0.12.1 and it went without a hitch! Part of the reason I believe is we recently upgraded the AWS RDS instance to 4 vCPUs from 2, so it's less CPU bound than before. The off peak CPU utilization has dropped from 40% to 10%, and that gives it more breathing room during the bootstrapping process.

**Comment by fishcakez** [comment] 2016-11-15 17:22
This issue is fixed in https://github.com/elixir-ecto/postgrex/commit/52488018cb0ca2f4132c8fa9c41cab7407746a90.

**Comment by Stingmaster** [comment] 2019-10-07 15:06
Faced with this error in production at the end of last week.
Suddenly the postgres began to consume 100% CPU and in elixir app I was getting timeout errors.

After much research, I found that the reason is in where clause of bootstrap_query (pg_catalog.pg_type on prod contains ~ 190.000 rows):
`AND (t.typelem = 0 OR t.typelem NOT IN (SELECT oid FROM pg_catalog.pg_type WHERE typrelid!=0))`

I had to rewrite the request for the next one and all stared to work:
`AND (t.typelem = 0 OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_type s WHERE s.typrelid!=0 AND s.oid = t.typelem))`

Please check this and may be update in the main branch.

**Comment by josevalim** [comment] 2019-10-07 19:46
@Stingmaster can you please provide the result of `explain analyze` of both queries in your production DB? It sounds a bit counter intuitive that one is faster than the other, so it would be nice to see what the database is planning. Thanks!

**Comment by Stingmaster** [comment] 2019-10-07 20:08
Yes, here they are:

```
EXPLAIN ANALYZE SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,
        coalesce(d.typelem, t.typelem), coalesce(r.rngsubtype, 0), ARRAY (
   SELECT a.atttypid
   FROM pg_attribute AS a
   WHERE a.attrelid = t.typrelid AND a.attnum > 0 AND NOT a.attisdropped
   ORDER BY a.attnum
 )
 FROM pg_type AS t
 LEFT JOIN pg_type AS d ON t.typbasetype = d.oid
 LEFT JOIN pg_range AS r ON r.rngtypid = t.oid OR (t.typbasetype <> 0 AND r.rngtypid = t.typbasetype)
 WHERE (t.typrelid = 0)
 AND (t.typelem = 0 OR t.typelem NOT IN (SELECT oid FROM pg_catalog.pg_type WHERE typrelid!=0));
                                                                        QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 Nested Loop Left Join  (cost=1000.42..323836377.44 rows=50115 width=124) (actual time=366558.199..374929.618 rows=173 loops=1)
   Join Filter: ((r.rngtypid = t.oid) OR ((t.typbasetype <> '0'::oid) AND (r.rngtypid = t.typbasetype)))
   Rows Removed by Join Filter: 1032
   ->  Nested Loop Left Join  (cost=1000.42..322013624.93 rows=50115 width=100) (actual time=366558.006..374928.569 rows=173 loops=1)
         ->  Gather  (cost=1000.00..321971143.62 rows=50115 width=96) (actual time=366557.982..374931.165 rows=173 loops=1)
               Workers Planned: 2
               Workers Launched: 2
               ->  Parallel Seq Scan on pg_type t  (cost=0.00..321965132.12 rows=20881 width=96) (actual time=366808.100..374853.461 rows=58 loops=3)
                     Filter: ((typrelid = '0'::oid) AND ((typelem = '0'::oid) OR (NOT (SubPlan 2))))
                     Rows Removed by Filter: 63445
                     SubPlan 2
                       ->  Materialize  (cost=0.00..7784.16 rows=131164 width=4) (actual time=0.002..14.127 rows=64241 loops=59778)
                             ->  Seq Scan on pg_type  (cost=0.00..6615.34 rows=131164 width=4) (actual time=0.002..17.885 rows=63029 loops=27485)
                                   Filter: (typrelid <> '0'::oid)
                                   Rows Removed by Filter: 28846
         ->  Index Scan using pg_type_oid_index on pg_type d  (cost=0.42..0.85 rows=1 width=8) (actual time=0.003..0.003 rows=0 loops=173)
               Index Cond: (t.typbasetype = oid)
   ->  Materialize  (cost=0.00..1.09 rows=6 width=8) (actual time=0.000..0.001 rows=6 loops=173)
         ->  Seq Scan on pg_range r  (cost=0.00..1.06 rows=6 width=8) (actual time=0.005..0.006 rows=6 loops=1)
   SubPlan 1
     ->  Index Scan using pg_attribute_relid_attnum_index on pg_attribute a  (cost=0.43..36.25 rows=8 width=6) (actual time=0.003..0.003 rows=0 loops=173)
           Index Cond: ((attrelid = t.typrelid) AND (attnum > 0))
           Filter: (NOT attisdropped)
 Planning Time: 2.295 ms
 Execution Time: 374934.505 ms
 
 
 EXPLAIN ANALYZE SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,
        coalesce(d.typelem, t.typelem), coalesce(r.rngsubtype, 0), ARRAY (
   SELECT a.atttypid
   FROM pg_attribute AS a                                                                             
   WHERE a.attrelid = t.typrelid AND a.attnum > 0 AND NOT a.attisdropped
   ORDER BY a.attnum
 )
 FROM pg_type AS t
 LEFT JOIN pg_type AS d ON t.typbasetype = d.oid
 LEFT JOIN pg_range AS r ON r.rngtypid = t.oid OR (t.typbasetype <> 0 AND r.rngtypid = t.typbasetype)
 WHERE (t.typrelid = 0)
   AND (t.typelem = 0 OR NOT EXISTS (SELECT 1 FROM pg_catalog.pg_type s WHERE s.typrelid!=0 AND s.oid = t.typelem));
                                                                         QUERY PLAN                                                                         
 -----------------------------------------------------------------------------------------------------------------------------------------------------------
  Nested Loop Left Join  (cost=9265.41..3449335.15 rows=50115 width=124) (actual time=261.623..269.074 rows=173 loops=1)
    Join Filter: ((r.rngtypid = t.oid) OR ((t.typbasetype <> '0'::oid) AND (r.rngtypid = t.typbasetype)))
    Rows Removed by Join Filter: 1032
    ->  Hash Left Join  (cost=9265.41..1626582.64 rows=50115 width=100) (actual time=261.530..268.427 rows=173 loops=1)
          Hash Cond: (t.typbasetype = d.oid)
          ->  Seq Scan on pg_type t  (cost=0.00..1614970.68 rows=50115 width=96) (actual time=174.124..175.247 rows=173 loops=1)
                Filter: ((typrelid = '0'::oid) AND ((typelem = '0'::oid) OR (NOT (SubPlan 2))))
                Rows Removed by Filter: 190334
                SubPlan 2
                  ->  Index Scan using pg_type_oid_index on pg_type s  (cost=0.42..8.44 rows=1 width=0) (actual time=0.002..0.002 rows=1 loops=59778)
                        Index Cond: (oid = t.typelem)
                        Filter: (typrelid <> '0'::oid)
                        Rows Removed by Filter: 0
          ->  Hash  (cost=6139.07..6139.07 rows=190507 width=8) (actual time=86.622..86.623 rows=190507 loops=1)
                Buckets: 131072  Batches: 4  Memory Usage: 2881kB
                ->  Seq Scan on pg_type d  (cost=0.00..6139.07 rows=190507 width=8) (actual time=0.030..48.719 rows=190507 loops=1)
    ->  Materialize  (cost=0.00..1.09 rows=6 width=8) (actual time=0.000..0.001 rows=6 loops=173)
          ->  Seq Scan on pg_range r  (cost=0.00..1.06 rows=6 width=8) (actual time=0.005..0.006 rows=6 loops=1)
    SubPlan 1
      ->  Index Scan using pg_attribute_relid_attnum_index on pg_attribute a  (cost=0.43..36.25 rows=8 width=6) (actual time=0.002..0.002 rows=0 loops=173)
            Index Cond: ((attrelid = t.typrelid) AND (attnum > 0))
            Filter: (NOT attisdropped)
  Planning Time: 0.866 ms
  Execution Time: 269.248 ms
```

**Closed** 2019-10-08 10:28 UTC
Labels: Kind:Bug, Level:Advanced, Note:Needs more info
