### ISSUE TITLE
Reload `oid` types when a new type is detected

### ISSUE THREAD

**Issue by stavro** [elixir-ecto/postgrex#243] opened 2016-09-27 22:05 UTC
Since we are already loading types initially, I think it would be amazing if we can trigger a refresh of the stored types when a new type is encountered.

Running some migrations is very painful with Postgrex & Ecto right now, because existing connections become broken.  I currently have to restart my web server after running migrations due to this, which I hope shouldn't be necessary long term.

``` elixir
{:ok, pid} = Postgrex.start_link(hostname: "localhost", username: "postgres", password: "postgres", database: "postgres")
Postgrex.query!(pid, "create type test_type as (name varchar);", [])
Postgrex.query!(pid, "select '(name)'::test_type", [])

** (RuntimeError) oid `319629` was not bootstrapped and lacks type information
[error] Postgrex.Protocol (#PID<0.350.0>) disconnected: ** (RuntimeError) oid `319629` was not bootstrapped and lacks type information
    (db_connection) lib/db_connection.ex:481: DBConnection.prepare_execute!/4
         (postgrex) lib/postgrex.ex:146: Postgrex.query!/4
```

**Comment by stavro** [comment] 2016-09-27 22:05
Spoke briefly with @fishcakez on IRC about this.

**Comment by fishcakez** [comment] 2016-09-27 22:08
We could disconnect when non-bootstrapped type encountered. This would trigger reconnection and rebootstrap would kick in. Then we would add the oid to ETS cache even if cant handle it.

**Comment by fishcakez** [comment] 2016-09-27 23:15
It turns we already do what I suggested and the actual bug is fixed in #244.

**Comment by mspanc** [comment] 2017-05-29 10:18
I have encountered this today when running migrations despite being marked as closed

```
12:14:21.597 [info]  == Running Agenda.Repo.Migrations.AssignBroadcastChannelsToWeeklyItems.up/0 forward

12:14:21.598 [error] Postgrex.Protocol (#PID<0.4912.0>) disconnected: ** (RuntimeError) oid `16540` was not bootstrapped and lacks type information

12:14:21.598 [debug] QUERY ERROR source="schedule_weekly_item" db=0.4ms
SELECT s0."id", s0."broadcast_content_type_id", s0."broadcast_channel_id", s0."name", s0."time_start", s0."time_stop", s0."on_monday", s0."on_tuesday", s0."on_wednesday", s0."on_thursday", s0."on_friday", s0."on_saturday", s0."on_sunday", s0."references", s0."extra", s0."priority", s0."composition", s0."tag_contents", s0."inserted_at", s0."updated_at" FROM "schedule_weekly_item" AS s0 []
** (RuntimeError) oid `16540` was not bootstrapped and lacks type information
    (ecto) lib/ecto/adapters/postgres/connection.ex:86: Ecto.Adapters.Postgres.Connection.prepare_execute/5
    (ecto) lib/ecto/adapters/sql.ex:243: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:431: Ecto.Adapters.SQL.execute_and_cache/7
    (ecto) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.execute/5
    (ecto) lib/ecto/repo/queryable.ex:35: Ecto.Repo.Queryable.all/4
    _build/dev/lib/agenda/priv/repo/migrations/20160620123932_assign_broadcast_channels_to_weekly_items.exs:24: Agenda.Repo.Migrations.AssignBroadcastChannelsToWeeklyItems.assign_broadcast_channels/0
    _build/dev/lib/agenda/priv/repo/migrations/20160620123932_assign_broadcast_channels_to_weekly_items.exs:5: Agenda.Repo.Migrations.AssignBroadcastChannelsToWeeklyItems.up/0
    (stdlib) timer.erl:197: :timer.tc/3
```

ecto 2.1.3
phoenix_ecto 3.2.3
postgrex 0.13.0

postgrex 0.13.0 I am using should contain a fix for this as it was released in Dec 2016 and fix was pulled 28 Sep 2016

**Comment by fishcakez** [comment] 2017-05-29 10:22
@mspanc this is working as intended, rather its a feature, not a bug. An initial crash occurs and then a reload.

**Comment by josevalim** [comment] 2017-05-29 13:23
I talked to @fishcakez and we will try to rebootstrap inline. We need to guarantee we don't run into an infinite loop though.

**Closed** 2017-05-31 11:20 UTC
Labels: Kind:Enhancement, Level:Advanced
